update
samaritanhu/Introduction-to-Algorithms pull request #22
Opened 2019-04-16 14:24 UTC by iamSmallY

add C 5.4,5.5

2019-04-16 14:32 UTC, qcmiao1998 requested changes
1. Split process into standalone functions.
2. No Chinese characters in STDOUT, it usually causes incorrect display.

2019-04-23 13:38 UTC, johnnychen94 commented
> Split process into standalone functions.

2019-04-26 10:02 UTC, qcmiao1998 requested changes
Use `#ifndef #define #endif` in the header file to avoid redefine mistake.

2019-04-27 15:05 UTC, qcmiao1998 approved these changes

2019-04-27 15:06 UTC, merged